#ifndef CONSOLE_H_INCLUDED
#define CONSOLE_H_INCLUDED
#ifdef __cplusplus
  extern "C" {
#endif

#include <windows.h>

#define TCLR_BLACK    0
#define TCLR_RED      FOREGROUND_RED
#define TCLR_GREEN    FOREGROUND_GREEN
#define TCLR_YELLOW   FOREGROUND_GREEN|FOREGROUND_RED
#define TCLR_BLUE     FOREGROUND_BLUE
#define TCLR_MAGENTA  FOREGROUND_BLUE|FOREGROUND_RED
#define TCLR_CYAN     FOREGROUND_BLUE|FOREGROUND_GREEN
#define TCLR_WHITE    FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_RED

#define TCLR_GREY     FOREGROUND_INTENSITY
#define TCLR_BRED     FOREGROUND_INTENSITY|FOREGROUND_RED
#define TCLR_BGREEN   FOREGROUND_INTENSITY|FOREGROUND_GREEN
#define TCLR_BYELLOW  FOREGROUND_INTENSITY|FOREGROUND_GREEN|FOREGROUND_RED
#define TCLR_BBLUE    FOREGROUND_INTENSITY|FOREGROUND_BLUE
#define TCLR_BMAGENTA FOREGROUND_INTENSITY|FOREGROUND_BLUE|FOREGROUND_RED
#define TCLR_BCYAN    FOREGROUND_INTENSITY|FOREGROUND_BLUE|FOREGROUND_GREEN
#define TCLR_BWHITE   FOREGROUND_INTENSITY|FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_RED

#define BCLR_BLACK    0
#define BCLR_RED      BACKGROUND_RED
#define BCLR_GREEN    BACKGROUND_GREEN
#define BCLR_YELLOW   BACKGROUND_GREEN|BACKGROUND_RED
#define BCLR_BLUE     BACKGROUND_BLUE
#define BCLR_MAGENTA  BACKGROUND_BLUE|BACKGROUND_RED
#define BCLR_CYAN     BACKGROUND_BLUE|BACKGROUND_GREEN
#define BCLR_WHITE    BACKGROUND_BLUE|BACKGROUND_GREEN|BACKGROUND_RED

#define BCLR_GREY     BACKGROUND_INTENSITY
#define BCLR_BRED     BACKGROUND_INTENSITY|BACKGROUND_RED
#define BCLR_BGREEN   BACKGROUND_INTENSITY|BACKGROUND_GREEN
#define BCLR_BYELLOW  BACKGROUND_INTENSITY|BACKGROUND_GREEN|BACKGROUND_RED
#define BCLR_BBLUE    BACKGROUND_INTENSITY|BACKGROUND_BLUE
#define BCLR_BMAGENTA BACKGROUND_INTENSITY|BACKGROUND_BLUE|BACKGROUND_RED
#define BCLR_BCYAN    BACKGROUND_INTENSITY|BACKGROUND_BLUE|BACKGROUND_GREEN
#define BCLR_BWHITE   BACKGROUND_INTENSITY|BACKGROUND_BLUE|BACKGROUND_GREEN|BACKGROUND_RED


void cursor_parameters (DWORD dwSize, BOOL bVisible);
void cursor_position (SHORT x, SHORT y);
int kbhit (void);
void console_title (const char *title);
void console_init (int max_x, int max_y);
void console_clear (void);
void console_finish (void);
void pset (int x, int y, char ch, WORD attr);
void vline (int x, int y0, int y1, char ch, WORD attr);
void hline (int y, int x0, int x1, char ch, WORD attr);
void box (int x0, int y0, int x1, int y1, WORD attr);
void clear (void);
void redraw (void);
void draw_string (int x, int y, const char *s, int len, WORD attr);

#ifdef __cplusplus
  }
#endif
#endif
